
ERROR:utils.service_parts:Error
Traceback (most recent call last):
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/dialects/postgresql/psycopg.py", line 583, in execute
    result = self.await_(self._cursor.execute(query, params, **kw))
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib/python3.13/site-packages/psycopg/cursor_async.py", line 97, in execute
    raise ex.with_traceback(None)
psycopg.errors.UniqueViolation: duplicate key value violates unique constraint "article"
DETAIL:  Key (article)=(string2) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/run/media/atitkov/sd_data/FastapiSQLAlchemyPytestAlembic/utils/service_parts.py", line 57, in add_parts
    await session.flush()
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/ext/asyncio/session.py", line 800, in flush
    await greenlet_spawn(self.sync_session.flush, objects=objects)
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
    ~~~~~~~~~~~^^^^^^^^^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.mapper,
        ^^^^^^^^^^^^
        uow.states_for_mapper_hierarchy(self.mapper, False, False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        uow,
        ^^^^
    )
    ^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        base_mapper,
        ^^^^^^^^^^^^
    ...<3 lines>...
        insert,
        ^^^^^^^
    )
    ^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
        statement,
        params,
        execution_options=execution_options,
    )
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/dialects/postgresql/psycopg.py", line 583, in execute
    result = self.await_(self._cursor.execute(query, params, **kw))
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib/python3.13/site-packages/psycopg/cursor_async.py", line 97, in execute
    raise ex.with_traceback(None)
sqlalchemy.exc.IntegrityError: (psycopg.errors.UniqueViolation) duplicate key value violates unique constraint "article"
DETAIL:  Key (article)=(string2) already exists.
[SQL: INSERT INTO test.parts (id, article, article_unit, serial_number_machine, alternative_article, name_eng, name_ru, material, weight_kg, size, part_type, description_custom, manufacturer, trade_mark, qty_in_unit, country_eng, s_code, path_catalog, path_documentation, path_photo, path_avatar, hashtags, create_at, comment) VALUES (%(id)s::UUID, %(article)s::VARCHAR, %(article_unit)s::VARCHAR, %(serial_number_machine)s::VARCHAR, %(alternative_article)s::VARCHAR, %(name_eng)s::VARCHAR, %(name_ru)s::VARCHAR, %(material)s::VARCHAR, %(weight_kg)s, %(size)s, %(part_type)s::VARCHAR, %(description_custom)s::VARCHAR, %(manufacturer)s::VARCHAR, %(trade_mark)s::VARCHAR, %(qty_in_unit)s::INTEGER, %(country_eng)s::VARCHAR, %(s_code)s::VARCHAR, %(path_catalog)s::VARCHAR, %(path_documentation)s::VARCHAR, %(path_photo)s::VARCHAR, %(path_avatar)s::VARCHAR, %(hashtags)s::VARCHAR, now(), %(comment)s::VARCHAR) RETURNING test.parts.create_at, test.parts.update_at]
[parameters: {'id': UUID('acbd359d-8048-47de-bdf5-e02f4053a15f'), 'article': 'string2', 'article_unit': 'string', 'serial_number_machine': 'string', 'alternative_article': 'string', 'name_eng': 'string', 'name_ru': 'string', 'material': 'string', 'weight_kg': 0.0, 'size': 0.0, 'part_type': 'string', 'description_custom': 'string', 'manufacturer': 'string', 'trade_mark': 'string', 'qty_in_unit': 0, 'country_eng': 'string', 's_code': 'string', 'path_catalog': 'string', 'path_documentation': 'string', 'path_photo': 'string', 'path_avatar': 'string', 'hashtags': 'string', 'comment': 'string'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
ERROR:utils.service_parts:Error
Traceback (most recent call last):
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/dialects/postgresql/psycopg.py", line 583, in execute
    result = self.await_(self._cursor.execute(query, params, **kw))
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib/python3.13/site-packages/psycopg/cursor_async.py", line 97, in execute
    raise ex.with_traceback(None)
psycopg.errors.UniqueViolation: duplicate key value violates unique constraint "article"
DETAIL:  Key (article)=(string2) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/run/media/atitkov/sd_data/FastapiSQLAlchemyPytestAlembic/utils/service_parts.py", line 57, in add_parts
    await session.flush()
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/ext/asyncio/session.py", line 800, in flush
    await greenlet_spawn(self.sync_session.flush, objects=objects)
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
    ~~~~~~~~~~~^^^^^^^^^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.mapper,
        ^^^^^^^^^^^^
        uow.states_for_mapper_hierarchy(self.mapper, False, False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        uow,
        ^^^^
    )
    ^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        base_mapper,
        ^^^^^^^^^^^^
    ...<3 lines>...
        insert,
        ^^^^^^^
    )
    ^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
        statement,
        params,
        execution_options=execution_options,
    )
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/dialects/postgresql/psycopg.py", line 583, in execute
    result = self.await_(self._cursor.execute(query, params, **kw))
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib64/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/home/atitkov/.cache/pypoetry/virtualenvs/fastapisqlalchemypytestalembic-s73ysBVS-py3.13/lib/python3.13/site-packages/psycopg/cursor_async.py", line 97, in execute
    raise ex.with_traceback(None)
sqlalchemy.exc.IntegrityError: (psycopg.errors.UniqueViolation) duplicate key value violates unique constraint "article"
DETAIL:  Key (article)=(string2) already exists.
[SQL: INSERT INTO test.parts (id, article, article_unit, serial_number_machine, alternative_article, name_eng, name_ru, material, weight_kg, size, part_type, description_custom, manufacturer, trade_mark, qty_in_unit, country_eng, s_code, path_catalog, path_documentation, path_photo, path_avatar, hashtags, create_at, comment) VALUES (%(id)s::UUID, %(article)s::VARCHAR, %(article_unit)s::VARCHAR, %(serial_number_machine)s::VARCHAR, %(alternative_article)s::VARCHAR, %(name_eng)s::VARCHAR, %(name_ru)s::VARCHAR, %(material)s::VARCHAR, %(weight_kg)s, %(size)s, %(part_type)s::VARCHAR, %(description_custom)s::VARCHAR, %(manufacturer)s::VARCHAR, %(trade_mark)s::VARCHAR, %(qty_in_unit)s::INTEGER, %(country_eng)s::VARCHAR, %(s_code)s::VARCHAR, %(path_catalog)s::VARCHAR, %(path_documentation)s::VARCHAR, %(path_photo)s::VARCHAR, %(path_avatar)s::VARCHAR, %(hashtags)s::VARCHAR, now(), %(comment)s::VARCHAR) RETURNING test.parts.create_at, test.parts.update_at]
[parameters: {'id': UUID('42d4eaf5-f7c5-4a3c-9680-42e447cdf40e'), 'article': 'string2', 'article_unit': 'string', 'serial_number_machine': 'string', 'alternative_article': 'string', 'name_eng': 'string', 'name_ru': 'string', 'material': 'string', 'weight_kg': 0.0, 'size': 0.0, 'part_type': 'string', 'description_custom': 'string', 'manufacturer': 'string', 'trade_mark': 'string', 'qty_in_unit': 0, 'country_eng': 'string', 's_code': 'string', 'path_catalog': 'string', 'path_documentation': 'string', 'path_photo': 'string', 'path_avatar': 'string', 'hashtags': 'string', 'comment': 'string'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
